spring:
  jpa:
    hibernate:
      #ddl-auto=none
    #show-sql=true
    properties:
      hibernate:
        #format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect    
      
  datasource:
    password:
    username: sa
    driverClassName: org.h2.Driver
    #url: jdbc:h2:file:/data/demo
    #url: jdbc:h2:./db/repository
    url: jdbc:h2:mem:microjavaj;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    
  h2:
    console:
      path: /h2
      enabled: true

logging:
  level:
    #org.hibernate.type: trace